server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
spring.data.redis.url=${REDIS_URL}
spring.cache.type=redis
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info
management.health.mail.enabled=false